### ISSUE TITLE
Type tests do not use any of TSConfig files from this repo

### ISSUE THREAD

**Issue by mrazauskas** [m4rw3r/graphql-query-joiner#4]
Thanks for give TSTyche a try! I am its author, nice to see you found it useful.

Just wanted to draw your attention that TSTyche uses compiler options from nearest `tsconfig.json` which includes files in questions. This means that a `tsconfig.json` which does not include the particular type test file gets ignored. (This is also how code editors pick up compiler options.)

In current setup the type test files are excluded in the [root TSConfig](https://github.com/m4rw3r/graphql-query-joiner/blob/main/tsconfig.json). This means that TSTyche has to fallback to its default compiler options: https://tstyche.org/guide/javascript-project#default-compiler-options

I just wanted to make sure, that this is exactly what you expect.

**Comment by m4rw3r** [comment]
Thank you for the awesome tool!

Good to know that it is operating with defaults, I don't think I intended that when I wrote it.

The goal of the `tsconfig.json` files in this repo is to provide TypeScript type-checking in the general case and for CI/CD. It is somewhat problematic in a monorepo where packages depend on each other but are supposed to be built separately (excluding the example app) since the build steps require the type-information but cannot use paths since they then get included in the build or raise errors due to being outside the package `rootDir` configured in the build-step.

So the build for this repo is a staged build, with first general type-checking across all packages without any compilation (main `tsconfig.json`), then generate `.d.ts` files using Rollup for each package separately, and finally build the packages individually without any path remapping now that they have types to reference (the `tsconfig.build.json` files).

This means that I want to be able to exclude the TSTyche test-files from the general CI/CD/build typechecking step since they fail type-checking on purpose, but still use the base `tsconfig.base.json` configuration for them.

I had a look at the configuration, but there does not seem to be any way to explicitly set the `tsconfig.json` file in TSTyche, besides using a different directory for the tests with its own `tsconfig.json`. Is this what you would suggest? Or do you have any other suggestions?

**Comment by mrazauskas** [comment]
Code editors do not have a way to use an arbitrary `tsconfig.json` as well. TSTyche is using the same TypeScript's API as code editors do. In a way I like this limitation, because what you see in the editor and in type test output is the same thing (`exclude` is respected by code editors too).

It is possible to keep test files next to source file and split them into projects using `references`. This is documented here: https://tstyche.org/guide/typescript-project#next-to-source-files

The problem is that `tsc --noEmit` does not work with `references`.

I find it the easiest to keep test files in separate directories. This is the model used in Jest's monorepo. I was helping there with types and especially with type tests. (TSTyche was born, because I wanted a better tool to handle those 1500 assertions hanging around.)

Separating test files into dedicated directories also help to isolate types of Jest globals. Otherwise they leak into source files too. I wish there was less complexity and also less magic in some parts of TypeScript.

**Comment by mrazauskas** [comment]
Actually it is enough to move type test file to separate folder and to add this `tsconfig.json`:

```json
{
  "extends": "../../tsconfig.json",
  "include": ["**/*"],
  "exclude": []
}
```

The root `exclude` can stay. It gets overridden here.

Or perhaps to create `tsconfig.build.json` (similar to `tsconfig.build.json`), which excludes type test files?

**Comment by m4rw3r** [comment]
I went with the separate check-file, makes sense to have the exclude in the check-step in that particular package. That way we can be sure that editors and other tools interpret the type-checks the same way.

**Comment by mrazauskas** [comment]
It feels organic here. I like the idea keeping the comment too. In general having the `.not.toBeCallableWith()` matcher would solve this issue.

My plan is to release TSTyche v1 next week. Current features are well tested and they deserve a stable release.

After that I will go back to `.toBeCallableWith()`.

Once again, thanks for using TSTyche. I was looking around to see what it is missing the most at the moment. All got clear (;
